// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHzJ1dNcgsE5GoUUXfXoaZOh42sddCO2Y',
    appId: '1:829562412262:web:b656b9f9d424dc99c3af27',
    messagingSenderId: '829562412262',
    projectId: 'chat-app-13953',
    authDomain: 'chat-app-13953.firebaseapp.com',
    storageBucket: 'chat-app-13953.appspot.com',
    measurementId: 'G-TT6YH2NPLF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGnifmBXpPpcnSpqlB3Z9-RwQyVgudjg0',
    appId: '1:829562412262:android:3299fce9548945b5c3af27',
    messagingSenderId: '829562412262',
    projectId: 'chat-app-13953',
    storageBucket: 'chat-app-13953.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYdrLTBl-ePQsh1UdjeAKNHqC2uNP7CoA',
    appId: '1:829562412262:ios:23e87379113d8b8ec3af27',
    messagingSenderId: '829562412262',
    projectId: 'chat-app-13953',
    storageBucket: 'chat-app-13953.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYdrLTBl-ePQsh1UdjeAKNHqC2uNP7CoA',
    appId: '1:829562412262:ios:23e87379113d8b8ec3af27',
    messagingSenderId: '829562412262',
    projectId: 'chat-app-13953',
    storageBucket: 'chat-app-13953.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHzJ1dNcgsE5GoUUXfXoaZOh42sddCO2Y',
    appId: '1:829562412262:web:8f0f2583c9c2faabc3af27',
    messagingSenderId: '829562412262',
    projectId: 'chat-app-13953',
    authDomain: 'chat-app-13953.firebaseapp.com',
    storageBucket: 'chat-app-13953.appspot.com',
    measurementId: 'G-36R2FG7KN4',
  );
}
